/*
Web Modeler REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 41f4f56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProjectDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectDto{}

// CreateProjectDto struct for CreateProjectDto
type CreateProjectDto struct {
	Name string `json:"name"`
}

type _CreateProjectDto CreateProjectDto

// NewCreateProjectDto instantiates a new CreateProjectDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectDto(name string) *CreateProjectDto {
	this := CreateProjectDto{}
	this.Name = name
	return &this
}

// NewCreateProjectDtoWithDefaults instantiates a new CreateProjectDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectDtoWithDefaults() *CreateProjectDto {
	this := CreateProjectDto{}
	return &this
}

// GetName returns the Name field value
func (o *CreateProjectDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProjectDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProjectDto) SetName(v string) {
	o.Name = v
}

func (o CreateProjectDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateProjectDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProjectDto := _CreateProjectDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProjectDto)

	if err != nil {
		return err
	}

	*o = CreateProjectDto(varCreateProjectDto)

	return err
}

type NullableCreateProjectDto struct {
	value *CreateProjectDto
	isSet bool
}

func (v NullableCreateProjectDto) Get() *CreateProjectDto {
	return v.value
}

func (v *NullableCreateProjectDto) Set(val *CreateProjectDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectDto(val *CreateProjectDto) *NullableCreateProjectDto {
	return &NullableCreateProjectDto{value: val, isSet: true}
}

func (v NullableCreateProjectDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


