/*
Web Modeler REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 41f4f56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MilestoneComparisonDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MilestoneComparisonDto{}

// MilestoneComparisonDto struct for MilestoneComparisonDto
type MilestoneComparisonDto struct {
	Url *string `json:"url,omitempty"`
}

// NewMilestoneComparisonDto instantiates a new MilestoneComparisonDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMilestoneComparisonDto() *MilestoneComparisonDto {
	this := MilestoneComparisonDto{}
	return &this
}

// NewMilestoneComparisonDtoWithDefaults instantiates a new MilestoneComparisonDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMilestoneComparisonDtoWithDefaults() *MilestoneComparisonDto {
	this := MilestoneComparisonDto{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *MilestoneComparisonDto) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneComparisonDto) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *MilestoneComparisonDto) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *MilestoneComparisonDto) SetUrl(v string) {
	o.Url = &v
}

func (o MilestoneComparisonDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MilestoneComparisonDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableMilestoneComparisonDto struct {
	value *MilestoneComparisonDto
	isSet bool
}

func (v NullableMilestoneComparisonDto) Get() *MilestoneComparisonDto {
	return v.value
}

func (v *NullableMilestoneComparisonDto) Set(val *MilestoneComparisonDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMilestoneComparisonDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMilestoneComparisonDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMilestoneComparisonDto(val *MilestoneComparisonDto) *NullableMilestoneComparisonDto {
	return &NullableMilestoneComparisonDto{value: val, isSet: true}
}

func (v NullableMilestoneComparisonDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMilestoneComparisonDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


