/*
Web Modeler REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 41f4f56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateMilestoneDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMilestoneDto{}

// UpdateMilestoneDto struct for UpdateMilestoneDto
type UpdateMilestoneDto struct {
	Name string `json:"name"`
}

type _UpdateMilestoneDto UpdateMilestoneDto

// NewUpdateMilestoneDto instantiates a new UpdateMilestoneDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMilestoneDto(name string) *UpdateMilestoneDto {
	this := UpdateMilestoneDto{}
	this.Name = name
	return &this
}

// NewUpdateMilestoneDtoWithDefaults instantiates a new UpdateMilestoneDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMilestoneDtoWithDefaults() *UpdateMilestoneDto {
	this := UpdateMilestoneDto{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateMilestoneDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateMilestoneDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateMilestoneDto) SetName(v string) {
	o.Name = v
}

func (o UpdateMilestoneDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMilestoneDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UpdateMilestoneDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMilestoneDto := _UpdateMilestoneDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMilestoneDto)

	if err != nil {
		return err
	}

	*o = UpdateMilestoneDto(varUpdateMilestoneDto)

	return err
}

type NullableUpdateMilestoneDto struct {
	value *UpdateMilestoneDto
	isSet bool
}

func (v NullableUpdateMilestoneDto) Get() *UpdateMilestoneDto {
	return v.value
}

func (v *NullableUpdateMilestoneDto) Set(val *UpdateMilestoneDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMilestoneDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMilestoneDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMilestoneDto(val *UpdateMilestoneDto) *NullableUpdateMilestoneDto {
	return &NullableUpdateMilestoneDto{value: val, isSet: true}
}

func (v NullableUpdateMilestoneDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMilestoneDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


