/*
Web Modeler REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 41f4f56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SortDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SortDto{}

// SortDto struct for SortDto
type SortDto struct {
	Field string `json:"field"`
	Direction string `json:"direction"`
}

type _SortDto SortDto

// NewSortDto instantiates a new SortDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSortDto(field string, direction string) *SortDto {
	this := SortDto{}
	this.Field = field
	this.Direction = direction
	return &this
}

// NewSortDtoWithDefaults instantiates a new SortDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSortDtoWithDefaults() *SortDto {
	this := SortDto{}
	return &this
}

// GetField returns the Field field value
func (o *SortDto) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *SortDto) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *SortDto) SetField(v string) {
	o.Field = v
}

// GetDirection returns the Direction field value
func (o *SortDto) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *SortDto) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *SortDto) SetDirection(v string) {
	o.Direction = v
}

func (o SortDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SortDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["direction"] = o.Direction
	return toSerialize, nil
}

func (o *SortDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"direction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSortDto := _SortDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSortDto)

	if err != nil {
		return err
	}

	*o = SortDto(varSortDto)

	return err
}

type NullableSortDto struct {
	value *SortDto
	isSet bool
}

func (v NullableSortDto) Get() *SortDto {
	return v.value
}

func (v *NullableSortDto) Set(val *SortDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSortDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSortDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSortDto(val *SortDto) *NullableSortDto {
	return &NullableSortDto{value: val, isSet: true}
}

func (v NullableSortDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSortDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


