/*
Web Modeler REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 41f4f56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateMilestoneDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMilestoneDto{}

// CreateMilestoneDto struct for CreateMilestoneDto
type CreateMilestoneDto struct {
	Name string `json:"name"`
	FileId string `json:"fileId"`
}

type _CreateMilestoneDto CreateMilestoneDto

// NewCreateMilestoneDto instantiates a new CreateMilestoneDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMilestoneDto(name string, fileId string) *CreateMilestoneDto {
	this := CreateMilestoneDto{}
	this.Name = name
	this.FileId = fileId
	return &this
}

// NewCreateMilestoneDtoWithDefaults instantiates a new CreateMilestoneDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMilestoneDtoWithDefaults() *CreateMilestoneDto {
	this := CreateMilestoneDto{}
	return &this
}

// GetName returns the Name field value
func (o *CreateMilestoneDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateMilestoneDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateMilestoneDto) SetName(v string) {
	o.Name = v
}

// GetFileId returns the FileId field value
func (o *CreateMilestoneDto) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *CreateMilestoneDto) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *CreateMilestoneDto) SetFileId(v string) {
	o.FileId = v
}

func (o CreateMilestoneDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMilestoneDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["fileId"] = o.FileId
	return toSerialize, nil
}

func (o *CreateMilestoneDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"fileId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMilestoneDto := _CreateMilestoneDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateMilestoneDto)

	if err != nil {
		return err
	}

	*o = CreateMilestoneDto(varCreateMilestoneDto)

	return err
}

type NullableCreateMilestoneDto struct {
	value *CreateMilestoneDto
	isSet bool
}

func (v NullableCreateMilestoneDto) Get() *CreateMilestoneDto {
	return v.value
}

func (v *NullableCreateMilestoneDto) Set(val *CreateMilestoneDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMilestoneDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMilestoneDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMilestoneDto(val *CreateMilestoneDto) *NullableCreateMilestoneDto {
	return &NullableCreateMilestoneDto{value: val, isSet: true}
}

func (v NullableCreateMilestoneDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMilestoneDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


